### ISSUE TITLE
License type?

### ISSUE THREAD

**Issue by mtwoodbury** [taswar/RedisForNetDevelopers#3]
Nice example. I see this repository is forked many times, but there is no open source license listed in the repository.  Reading over your blog, it seems your intention is to make it freely available. Would you be amenable to adding a license type to the readme file, such as https://opensource.org/licenses/MIT?

Great example BTW. I learned a lot.

**Comment by taswar** [comment]
I have added MIT license to my repo now :) Glad you learned I might make a free ebook out of it.
